### ISSUE TITLE
#handle_multiple_response Fails to handle Server Error Response

### ISSUE THREAD

**Issue by Pavonis** [retain-ai/prosperworks-ruby#3]
**Issue:**
When performing an operation that makes use of the `#handle_multiple_response` pathway in `connect.rb`, such as search operations against the objects, an unhandled exception is thrown as the client attempts to apply a function against a non enumerable entity.

**Impact:** 
When an error occurs connecting to the API, the client throws an exception, rather than allowing the client to respond to the Error condition returned from the server. If unhandled, the calling code would terminate.

**Proposed Solution:**
In `ProsperWorks::ApiOperations::Connect#handle_multiple_response`, modify the Error comparison to compare against the `ProsperWorks::Errors::Base` class, rather than the containing module. Additionally, add some tests to verify this behavior.

**Sample Stacktrace:**

```ruby
NoMethodError: undefined method `map' for ProsperWorks::Errors::RateLimit:Class
Did you mean?  tap
	.rvm/gems/ruby-2.4.3/gems/prosperworks-ruby-0.2.0/lib/prosperworks/api_operations/connect.rb:75:in `handle_multiple_response'
	.rvm/gems/ruby-2.4.3/gems/prosperworks-ruby-0.2.0/lib/prosperworks/api_operations/search.rb:11:in `search'
	/lib/prosperworks_extractor.rb:58:in `retrieve'
	.rvm/gems/ruby-2.4.3/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	.rvm/gems/ruby-2.4.3/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	.rvm/gems/ruby-2.4.3/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	.rvm/gems/ruby-2.4.3/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	.rvm/gems/ruby-2.4.3/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	.rvm/gems/ruby-2.4.3/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	.rvm/gems/ruby-2.4.3/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	.rvm/gems/ruby-2.4.3/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by Pavonis** [comment]
During Code Review, also found this similar pattern in:

- `ProsperWorks::ApiOperations::Delete#handle_delete_response`

A fix should address the issue for this codepath, too.
